# Generated by Django 4.2.3 on 2023-07-11 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('auto', '0002_rename_year_auto_state_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routs', to='auto.auto')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routs', to='drivers.driver')),
            ],
        ),
    ]
