# Generated by Django 4.2.3 on 2023-07-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='year',
            new_name='state_number',
        ),
    ]
