# Generated by Django 4.2.3 on 2024-08-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_rename_year_auto_state_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auto',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
