# Generated by Django 4.2.3 on 2024-08-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_auto_make_alter_auto_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='year',
            field=models.IntegerField(default=10),
        ),
    ]
